export const categoriesInitials = [
  {
    name: 'Supermercado',
    description: '',
    default: true,
    area: 'Mercado',
    areaId: null,
  },
  {
    name: 'Carniceria',
    description: '',
    default: true,
    area: 'Mercado',
    areaId: null,
  },
  {
    name: 'Verduleria',
    description: '',
    default: true,
    area: 'Mercado',
    areaId: null,
  },
  {
    name: 'Combustible',
    description: '',
    default: true,
    area: 'Transporte',
    areaId: null,
  },
  {
    name: 'Taxi/Uber',
    description: '',
    default: true,
    area: 'Transporte',
    areaId: null,
  },
  {
    name: 'Visita Medica',
    description: '',
    default: true,
    area: 'Salud',
    areaId: null,
  },
  {
    name: 'Farmacia',
    description: '',
    default: true,
    area: 'Salud',
    areaId: null,
  },
  {
    name: 'Cine',
    description: '',
    default: true,
    area: 'Entretenimiento',
    areaId: null,
  },
  {
    name: 'Parque',
    description: '',
    default: true,
    area: 'Entretenimiento',
    areaId: null,
  },
  {
    name: 'Colegio/Escuela',
    description: '',
    default: true,
    area: 'Educacion',
    areaId: null,
  },
  {
    name: 'Universidad',
    description: '',
    default: true,
    area: 'Educacion',
    areaId: null,
  },
  {
    name: 'Pasajes',
    description: '',
    default: true,
    area: 'Viaje',
    areaId: null,
  },
  {
    name: 'Alojamiento',
    description: '',
    default: true,
    area: 'Viaje',
    areaId: null,
  },
  {
    name: 'Ropa',
    description: '',
    default: true,
    area: 'Vestimenta',
    areaId: null,
  },
  {
    name: 'Calzado',
    description: '',
    default: true,
    area: 'Vestimenta',
    areaId: null,
  },
  {
    name: 'Ropa Interior',
    description: '',
    default: true,
    area: 'Vestimenta',
    areaId: null,
  },
  {
    name: 'Sueldo Principal',
    description: '',
    default: true,
    area: 'Ingresos',
    areaId: null,
  },
  {
    name: 'Trabajos Particulares',
    description: '',
    default: true,
    area: 'Ingresos',
    areaId: null,
  },
]