export const categoriesInitials = [
  {
    name: 'Supermercado',
    description: '',
    default: true,
    color: '#FF5630',
    icon: 'Market',
    area: 'Mercado',
    areaId: null,
  },
  {
    name: 'Carniceria',
    description: '',
    default: true,
    color: '#04717F',
    icon: 'Cow',
    area: 'Mercado',
    areaId: null,
  },
  {
    name: 'Verduleria',
    description: '',
    default: true,
    color: '#04717F',
    icon: 'Vegetable',
    area: 'Mercado',
    areaId: null,
  },
  {
    name: 'Combustible',
    description: '',
    default: true,
    color: '#B71D18',
    icon: 'Gas',
    area: 'Transporte',
    areaId: null,
  },
  {
    name: 'Taxi/Uber',
    description: '',
    default: true,
    color: '#B71D18',
    icon: 'Taxi',
    area: 'Transporte',
    areaId: null,
  },
  {
    name: 'Visita Medica',
    description: '',
    default: true,
    color: '#FFAC82',
    icon: 'Medic',
    area: 'Salud',
    areaId: null,
  },
  {
    name: 'Farmacia',
    description: '',
    default: true,
    color: '#FFAC82',
    icon: 'Medication',
    area: 'Salud',
    areaId: null,
  },
  {
    name: 'Cine',
    description: '',
    default: true,
    color: '#C684FF',
    icon: 'Film',
    area: 'Entretenimiento',
    areaId: null,
  },
  {
    name: 'Colegio/Escuela',
    description: '',
    default: true,
    color: '#04717F',
    icon: 'School',
    area: 'Educacion',
    areaId: null,
  },
  {
    name: 'Universidad',
    description: '',
    default: true,
    color: '#04717F',
    icon: 'Graduate',
    area: 'Educacion',
    areaId: null,
  },
  {
    name: 'Boletos Viaje',
    description: '',
    default: true,
    color: '#D0ECFE',
    icon: 'Ticket',
    area: 'Viaje',
    areaId: null,
  },
  {
    name: 'Alojamiento',
    description: '',
    default: true,
    color: '#D0ECFE',
    icon: 'Flight',
    area: 'Viaje',
    areaId: null,
  },
  {
    name: 'Ropa',
    description: '',
    default: true,
    color: '#DB29BA',
    icon: 'Wear',
    area: 'Vestimenta',
    areaId: null,
  },
  {
    name: 'Calzado',
    description: '',
    default: true,
    color: '#DB29BA',
    icon: 'Feet',
    area: 'Vestimenta',
    areaId: null,
  },
  {
    name: 'Ropa Interior',
    description: '',
    color: '#DB29BA',
    icon: 'Shock',
    default: true,
    area: 'Vestimenta',
    areaId: null,
  },
  {
    name: 'Sueldo Principal',
    description: '',
    default: true,
    color: '#075405',
    icon: 'HandMoney',
    area: 'Ingresos',
    areaId: null,
  },
  {
    name: 'Otros ingresos',
    description: '',
    default: true,
    color: '#075405',
    icon: 'Invoice',
    area: 'Ingresos',
    areaId: null,
  },
]